const DEFAULT_API="https://minecraft-launch-api.workers.dev";
let apiUrl=localStorage.getItem("mc_api_url")||DEFAULT_API,clientId=localStorage.getItem("mc_client_id")||"f8cdef31-a31e-4b4a-93e4-5f571e91255a",selected=localStorage.getItem("mc_version")||"",account=null,versions=[];
const $=id=>document.getElementById(id),basePath=location.pathname.endsWith("/")?location.pathname:location.pathname.replace(/[^/]+$/,"/");
function setStatus(t){$("status").textContent=t}
function renderAccount(){const name=account?.name||"未登入";$("account").textContent=name;$("headerAccount").textContent=name;$("login").hidden=!!account;$("logout").hidden=!account;const skin=account?.skins?.[0]?.url;$("avatar").src=skin||"";$("avatar").style.display=skin?"block":"none"}
function renderVersions(){$("currentVersion").textContent=selected||versions[0]?.id||"—";$("versionList").innerHTML=versions.map(v=>"<div class='version'><span>Minecraft Java "+v.id+"<small>"+(v.releaseTime?new Date(v.releaseTime).toLocaleDateString():"")+"</small></span><button data-version='"+v.id+"'>"+(v.id===selected?"已選擇":"選擇")+"</button></div>").join("");document.querySelectorAll(".version button").forEach(b=>b.onclick=()=>{selected=b.dataset.version;localStorage.setItem("mc_version",selected);renderVersions()})}
async function api(path,options={}){const r=await fetch(apiUrl.replace(/\/$/,"")+path,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"API HTTP "+r.status);return data}
async function loadVersions(){try{const data=await api("/api/versions");versions=data.versions||[];if(!versions.some(v=>v.id===selected))selected=versions[0]?.id||"";renderVersions();$("apiStatus").textContent="Online";$("cloudState").textContent="Online"}catch(e){$("apiStatus").textContent="Offline";$("cloudState").textContent="連線失敗";$("versionList").innerHTML="<div class='notice'>"+e.message+"</div>"}}
function createMsal(){if(!clientId)throw new Error("請先到「設定」輸入 Microsoft Client ID。");return new msal.PublicClientApplication({auth:{clientId,authority:"https://login.microsoftonline.com/consumers",redirectUri:location.origin+basePath},cache:{cacheLocation:"sessionStorage"}})}
let msalApp;
async function login(){try{setStatus("正在開啟 Microsoft 登入…");msalApp=createMsal();const result=await msalApp.loginPopup({scopes:["XboxLive.signin","offline_access"]});account=await api("/api/account",{method:"POST",body:JSON.stringify({accessToken:result.accessToken})});renderAccount();setStatus("Microsoft 與 Minecraft 授權完成")}catch(e){setStatus("登入失敗："+e.message)}}
async function restore(){if(!clientId)return;try{msalApp=createMsal();const a=msalApp.getAllAccounts();if(!a.length)return;const result=await msalApp.acquireTokenSilent({account:a[0],scopes:["XboxLive.signin"]});account=await api("/api/account",{method:"POST",body:JSON.stringify({accessToken:result.accessToken})});renderAccount();setStatus("已登入 "+account.name)}catch(e){console.warn(e)}}
$("login").onclick=login;$("logout").onclick=()=>{if(msalApp)msalApp.logoutPopup().catch(()=>{});account=null;renderAccount();setStatus("已登出")};$("play").onclick=()=>{$("status").textContent=account?"已選擇 "+(selected||"最新正式版")+"。網頁版無法直接啟動本機 Java，請使用 Desktop Agent。":"請先登入 Microsoft。"};$("saveSettings").onclick=async()=>{clientId=$("clientId").value.trim();apiUrl=$("apiUrl").value.trim()||DEFAULT_API;localStorage.setItem("mc_client_id",clientId);localStorage.setItem("mc_api_url",apiUrl);setStatus("設定已儲存");await loadVersions()};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(b.dataset.page).classList.add("active");document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("clientId").value=clientId;$("apiUrl").value=apiUrl;renderAccount();loadVersions().then(restore);